language: c
compiler: 
	-gcc
before_install:
	- sudo apt-get update
	- sudo apt-get install -qq liblzma-dev
    - sudo apt-get install -qq zlib1g-dev
    - sudo apt-get install -qq xsltproc docbook-xsl
	
script: make m7_defconfig && make